### ISSUE TITLE
System updates app will not use up to date translations because "r" qualifier takes precedence

### ISSUE THREAD

**Issue by yankarinRG** [PixelExperience/packages_apps_Updates#1]
It is impossible for the System updates app with package name org.pixelexperience.ota to use the latest up to date Crowdin translations because the resources with the region code qualifier **r** take precedence over the resources not having it.

For example, _values-it-rIT_ with old translations takes precedence over _values-it_ with new translations and because of this, old and not up to date translations will be used.
The **r** qualifier is optional and is used to differentiate a country where the same language is spoken.
For example _values-es_ is the general spanish resource folder which is used if the phone language is set to spanish, regardless of country (Spain, Mexico or Argentina, for example).
If we also want to specify the country, then we add the **r** qualifier.
In this case, _values-es-rES_ is for spanish speaking users from Spain, _values-es-rAR_ for spanish speaking users from Argentina and _values-es-rMX_ for spanish speaking users from Mexico.

General form:
- values-**cc**
_where **cc** is the 2 letter [ISO 639-1](http://www.loc.gov/standards/iso639-2/php/code_list.php) language code_
- values-**cc**-r**RC**
_where **cc** is like before and **RC** is the 2 letter [ISO 3166-1-alpha-2](https://www.iso.org/obp/ui/#iso:pub:PUB500001:en) region code (in UPPERCASE)_

Having said that, **the way to fix this is the following**:
- for languages which have a single country, in this case, like italian, french or german, then DON'T use the **r** qualifier. We'll have_values-it_, _values-fr_ and _values-de_, for example.
- for languages which have multiple countries, like spanish, then use the general and region specific  qualifier **r**. We'll have _values-es_, _values-es-rES_, _values-es-rAR_ and _values-es-rMX_, for example.

**This rule SHOULD BE applied to all Pixel Experience projects, for the correct functionality.**

@jhenrique09 please check this, this is pretty urgent.

**Comment by jhenrique09** [comment]
For example, If the string isn't available on values-es-rMX, values-es will be used as fallback.

There's nothing wrong with it, i use crowdin since 2016

**Comment by yankarinRG** [comment]
_values-it_ is the **updated** resource folder (3 months ago)
_values-it-rIT_ is the **outdated** resource folder (9 months ago)

This means when you built the Crowdin project, probably 3 months ago, the script imported the translations into _values-it_ but, since _values-it-rIT_ has more priority than _values-it_, then _values-it-rIT_ resources will be used and hence we have outdated translations.

This happens with a lot of languages, for example ar, bg, ca, cs etc...
